[tool.poetry]
name = "spacy-hungarian-models"
version = "0.4.0"
description = "Hungarian models for spaCy"
authors = ["Gyorgy Orosz <gyorgy@orosz.link>"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"
spacy = "~3.0.5"
lemmy = "^2.1.0"
spacy-ray = "^0.1.0"
wandb = "^0.10.23"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
