[tool.poetry]
name = "huspacy"
version = "0.4.0-alpha.4"
description = "HuSpaCy: industrial strength Hungarian natural language processing"
authors = ["György Orosz <gyorgy@orosz.link>"]
maintainers = ["György Orosz <gyorgy@orosz.link>"]
keywords = ["nlp", "huspacy", "Hungarian", "text processing", "pos tagging", "lemmatization", "ner", "parsing"]
license = "Apache 2.0"
homepage = "https://github.com/spacy-hu/spacy-hungarian-models"
readme = "README.md"
classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: Apache Software License',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Topic :: Text Processing',
    'Topic :: Text Processing :: Linguistic',
    'Topic :: Scientific/Engineering',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
    'Topic :: Scientific/Engineering :: Human Machine Interfaces',
    'Topic :: Scientific/Engineering :: Information Analysis',
]
packages = [
    {include = "huspacy"},
]


[tool.poetry.dependencies]
python = "^3.7.1"
spacy = "^3.2.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
