project: spacy_trf_ner
command:
- python
- -m
- spacy
- train
- ./configs/parser.cfg
- --output
- ../transformer_models/sweep_ner_merged
- --gpu-id
- 0
- ${args}
method: grid
parameters:
  nlp.lang:
    values:
    - hu
  paths.dev:
    values:
      - ../data/processed/ner_merged/dev.spacy
  paths.train:
    values:
      - ../data/processed/ner_merged/train.spacy
  training.dropout:
    values:
    - 0.1
    - 0.2
    - 0.3
  training.optimizer.L2:
    values:
    - 0.1
    - 0.01
    - 0.001