project: spacy_trf_ner
command:
- python
- -m
- spacy
- train
- ./configs/tagger_lemma.cfg
- --output
- ../transformer_models/sweep_ner_merged
- --gpu-id
- 0
- --nlp.lang=hu
- --path.train
- ../data/processed/ner_merged/train.spacy
- --path.dev
- ../data/processed/ner_merged/dev.spacy
- ${args}
method: grid
parameters:
  components.experimental_edit_tree_lemmatizer.top_k:
    values:
      - 1
      - 2
      - 3
  nlp.lang:
    values:
      - hu
  paths.dev:
    values:
      - ../data/processed/ner_merged/dev.spacy
  paths.train:
    values:
      - ../data/processed/ner_merged/train.spacy
  training.dropout:
    values:
    - 0.1
    - 0.2
    - 0.3
  training.optimizer.L2:
    values:
    - 0.1
    - 0.01
    - 0.001