project: spacy_trf_ner
command:
- python
- -m
- spacy
- train
- ./configs/ner.cfg
- --output
- ../transformer_models/sweep_ner_merged
- --gpu-id
- 0
- --nlp.lang=hu
- --path.train
- ../data/processed/ner_merged/train.spacy
- --path.dev
- ../data/processed/ner_merged/dev.spacy
- ${args}
method: bayes
metric:
  name: ents_f #parser, tagger
  goal: maximize
parameters:
  nlp.lang:
    values:
    - hu
  training.dropout:
    values:
    - 0.1
    - 0.2
    - 0.3
  training.optimizer.L2:
    values:
    - 0.01
    - 0.1
    - 0.001